"""
40K Army Builder — CSV to JSON Conversion Script
Reads nine CSV exports from the Excel workbook and outputs:
  - units.json
  - keywords.json
  - rules.json

config.json is hand-authored and not generated by this script.

Input directory:  C:/Users/meowz/Documents/Warhammer/40K/Tool/JSON/csv/
Output directory: C:/Users/meowz/Documents/Warhammer/40K/Tool/JSON/

Usage:
    python convert_to_json.py
"""

import csv
import json
import os
import re
import sys
from collections import defaultdict

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

INPUT_DIR = os.path.join(
    "C:\\", "Users", "meowz", "Documents", "Warhammer", "40K", "Tool", "JSON", "csv"
)
OUTPUT_DIR = os.path.join(
    "C:\\", "Users", "meowz", "Documents", "Warhammer", "40K", "Tool", "JSON"
)

# CSV filenames (must match your Excel export names exactly)
CSV_FILES = {
    "unit_stats":        "Unit_Stats.csv",
    "unit_weapons":      "Unit_Weapons.csv",
    "unit_wargear":      "Unit_Wargear_Options.csv",
    "unit_points":       "Unit_Points.csv",
    "unit_abilities":    "Unit_Abilities.csv",
    "unit_other":        "Unit_Other_Options.csv",
    "rules":             "Rules.csv",
    "keywords":          "Keywords.csv",
    "weapon_abilities":  "Weapon_Abilities.csv",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def read_csv(filepath):
    """Read a CSV file and return a list of dicts (one per row)."""
    rows = []
    try:
        with open(filepath, encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append(row)
    except FileNotFoundError:
        print(f"ERROR: CSV file not found: {filepath}")
        sys.exit(1)
    return rows


def weapon_base(name):
    """Normalize a weapon name to its family base for matching: lowercase,
    drop any ' - profile' suffix, collapse whitespace. Used to detect when a
    flat wargear swap targets a family a bundle already manages."""
    if not name:
        return ""
    s = str(name).lower()
    s = re.split(r"\s+[\u2013\u2014-]\s+", s)[0]
    return " ".join(s.split())


def clean(value):
    """
    Convert a CSV cell value to the appropriate Python type.
    - Empty string / whitespace-only -> None
    - "Yes" / "No" -> True / False
    - Numeric strings -> int (if no decimal) or leave as str for fields
      that intentionally store dice expressions (handled per-field below)
    - Fixes backslash-escaped inch marks (6\\" or trailing 6\\) -> 6"
    """
    if value is None:
        return None
    v = value.strip()
    if v == "":
        return None
    if v.lower() == "yes":
        return True
    if v.lower() == "no":
        return False
    # Fix backslash-escaped inch marks from Excel CSV export
    v = v.replace('\\"', '"')
    if v.endswith('\\'):
        v = v[:-1] + '"'
    # Fix UTF-8 em-dash/en-dash misread as latin1 (â\x80\x93 -> -)
    v = v.replace('â', ' - ').replace('â', ' - ')
    # Collapse any double spaces introduced
    import re as _re
    v = _re.sub(r'  +', ' ', v).strip()
    return v


def to_int(value):
    """Convert to int, or None if blank."""
    v = clean(value)
    if v is None:
        return None
    try:
        return int(v)
    except (ValueError, TypeError):
        return v  # Return as string if not cleanly an int (safety fallback)


def split_list(value):
    """
    Convert a comma-separated string to a list of stripped strings.
    Returns an empty list if the value is blank.
    """
    v = clean(value)
    if v is None:
        return []
    return [item.strip() for item in v.split(",") if item.strip()]


def make_key(row, fields):
    """Build a tuple key from specified field names."""
    return tuple(clean(row.get(f, "")) for f in fields)


# ---------------------------------------------------------------------------
# Load all CSVs
# ---------------------------------------------------------------------------

def load_all(input_dir):
    data = {}
    for key, filename in CSV_FILES.items():
        filepath = os.path.join(input_dir, filename)
        data[key] = read_csv(filepath)
        print(f"  Loaded {len(data[key])} rows from {filename}")
    return data


def load_bundles(bundles_path):
    """
    Load the bundled-swap definition file and index it by (army_name, unit_name).
    Optional: a missing file is not an error (a faction may have no bundles).
    Each unit maps to its bundle record (option_group + endpoints), which the
    converter attaches to the unit object as 'bundled_swaps'.
    """
    if not bundles_path or not os.path.isfile(bundles_path):
        print(f"  No bundles file at {bundles_path} — building without bundled swaps.")
        return {}
    with open(bundles_path, encoding="utf-8") as f:
        doc = json.load(f)
    index = {}
    for rec in doc.get("bundles", []):
        army = (rec.get("army_name") or "").strip()
        unit = (rec.get("unit_name") or "").strip()
        if not army or not unit:
            print(f"  WARNING: bundle record missing army_name/unit_name — skipped.")
            continue
        eps = rec.get("endpoints", [])
        defaults = [e for e in eps if e.get("is_default")]
        if len(defaults) != 1:
            print(f"  WARNING: {army}/{unit} has {len(defaults)} default endpoints "
                  f"(expected exactly 1) — check bundled_swaps.json.")
        # A unit may carry more than one independent mutually-exclusive group
        # (e.g. a ranged axis and a melee axis). Accumulate groups into a list.
        index.setdefault((army, unit), []).append({
            "model_group":  rec.get("model_group"),
            "option_group": rec.get("option_group"),
            "endpoints":    eps,
        })
    print(f"  Loaded bundled swaps for {len(index)} unit(s).")
    return index


# ---------------------------------------------------------------------------
# Build keywords.json
# ---------------------------------------------------------------------------

def build_keywords(rows):
    """
    Simple lookup: list of { keyword_name, keyword_description }
    """
    result = []
    for row in rows:
        name = clean(row.get("Keyword Name"))
        desc = clean(row.get("Keyword Description"))
        if name:
            result.append({
                "keyword_name": name,
                "keyword_description": desc
            })
    return result


# ---------------------------------------------------------------------------
# Build rules.json
# ---------------------------------------------------------------------------

def build_rules(rows):
    """
    Simple lookup: list of { rule_name, rule_description }
    """
    result = []
    for row in rows:
        name = clean(row.get("Rule Name"))
        desc = clean(row.get("Rule Description"))
        if name:
            result.append({
                "rule_name": name,
                "rule_description": desc
            })
    return result


# ---------------------------------------------------------------------------
# Build abilities.json
# ---------------------------------------------------------------------------

def build_abilities(rows):
    """
    Simple lookup: list of { ability_name, ability_description }
    """
    result = []
    for row in rows:
        name = clean(row.get("Unit Ability Name"))
        desc = clean(row.get("Unit Ability Description"))
        if name:
            result.append({
                "ability_name": name,
                "ability_description": desc
            })
    return result


# ---------------------------------------------------------------------------
# Build weapon_abilities.json
# ---------------------------------------------------------------------------

def build_weapon_abilities(rows):
    """
    Simple lookup: list of { weapon_ability_name, weapon_ability_description }
    """
    result = []
    for row in rows:
        name = clean(row.get("Weapon Ability Name"))
        desc = clean(row.get("Weapon Ability Description"))
        if name:
            result.append({
                "weapon_ability_name": name,
                "weapon_ability_description": desc
            })
    return result


# ---------------------------------------------------------------------------
# Build units.json
# ---------------------------------------------------------------------------

def build_units(data):
    """
    Join all unit-related tabs on Army Name + Unit Name + Model Group
    and produce the nested structure defined in D26.
    """

    stats_rows      = data["unit_stats"]
    weapons_rows    = data["unit_weapons"]
    wargear_rows    = data["unit_wargear"]
    points_rows     = data["unit_points"]
    abilities_rows  = data["unit_abilities"]
    other_rows      = data["unit_other"]
    bundles         = data.get("bundles", {})

    # ------------------------------------------------------------------
    # Index supporting tabs by (Army Name, Unit Name, Model Group)
    # Points tab uses only (Army Name, Unit Name)
    # ------------------------------------------------------------------

    # Weapons: one list per (army, unit, model_group)
    weapons_by_key = defaultdict(list)
    for row in weapons_rows:
        key = make_key(row, ["Army Name", "Unit Name", "Model Group"])
        weapons_by_key[key].append(row)

    # Wargear options
    wargear_by_key = defaultdict(list)
    for row in wargear_rows:
        key = make_key(row, ["Army Name", "Unit Name", "Model Group"])
        wargear_by_key[key].append(row)

    # Other options
    other_by_key = defaultdict(list)
    for row in other_rows:
        key = make_key(row, ["Army Name", "Unit Name", "Model Group"])
        other_by_key[key].append(row)

    # Abilities
    abilities_by_key = defaultdict(list)
    for row in abilities_rows:
        key = make_key(row, ["Army Name", "Unit Name", "Model Group"])
        abilities_by_key[key].append(row)

    # Points: keyed by (army, unit) only
    points_by_key = {}
    for row in points_rows:
        key = make_key(row, ["Army Name", "Unit Name"])
        points_by_key[key] = row

    # ------------------------------------------------------------------
    # Group stats rows by army, then by unit
    # ------------------------------------------------------------------

    # armies_dict: { army_name: { unit_name: [stat_rows] } }
    armies_dict = defaultdict(lambda: defaultdict(list))
    for row in stats_rows:
        army = clean(row.get("Army Name"))
        unit = clean(row.get("Unit Name"))
        if army and unit:
            armies_dict[army][unit].append(row)

    # ------------------------------------------------------------------
    # Build output per army
    # ------------------------------------------------------------------

    output = []

    for army_name, units_dict in armies_dict.items():
        army_obj = {
            "army": army_name,
            "units": []
        }

        for unit_name, stat_rows in units_dict.items():

            # unit_type is the same across all model groups — take from first row
            unit_type = clean(stat_rows[0].get("Unit Type"))

            # ----------------------------------------------------------
            # model_groups
            # ----------------------------------------------------------
            model_groups = []
            for row in stat_rows:
                mg = clean(row.get("Model Group"))
                mg_key = (clean(row.get("Army Name")), unit_name, mg)

                model_group_obj = {
                    "model_group":              mg,
                    # Stats
                    "M":                        clean(row.get("M")),
                    "T":                        to_int(row.get("T")),
                    "SV":                       to_int(row.get("SV")),
                    "INV":                      to_int(row.get("INV")),
                    "INV_Condition":            clean(row.get("INV_Condition")),
                    "FNP":                      to_int(row.get("FNP")),
                    "FNP_Condition":            clean(row.get("FNP_Condition")),
                    "W":                        to_int(row.get("W")),
                    "LD":                       to_int(row.get("LD")),
                    "OC":                       to_int(row.get("OC")),
                    # Leader fields
                    "leader_ability_name":      clean(row.get("Leader Ability Name")),
                    "leader_eligible_units":    split_list(row.get("Leader Eligible Units", "")),
                    "co_leader_eligible_with":  split_list(row.get("Co-Leader Eligible With", "")),
                    "leader_restrictions":      clean(row.get("Leader Restrictions")),
                    # Reference lists (names only)
                    "unit_ability_names":       split_list(row.get("Unit Ability Names", "")),
                    "rule_names":               split_list(row.get("Rule Names", "")),
                    "keyword_names":            split_list(row.get("Keyword Names", "")),
                }
                model_groups.append(model_group_obj)

            # ----------------------------------------------------------
            # weapons
            # ----------------------------------------------------------
            weapons = []
            for row in weapons_rows:
                if (clean(row.get("Army Name")), clean(row.get("Unit Name"))) != (army_name, unit_name):
                    continue
                mg = clean(row.get("Model Group"))
                weapon_obj = {
                    "model_group":          mg,
                    "weapon_type":          clean(row.get("Weapon Type")),
                    "weapon_name":          clean(row.get("Weapon Name")),
                    "range":                clean(row.get("Range")),
                    "A":                    clean(row.get("A")),       # char: may be D6, 2D6+1 etc.
                    "BS":                   clean(row.get("BS")),
                    "WS":                   clean(row.get("WS")),
                    "S":                    to_int(row.get("S")),
                    "AP":                   to_int(row.get("AP")),
                    "D":                    clean(row.get("D")),       # char: may be D3, D6+1 etc.
                    "weapon_ability_names": split_list(row.get("Weapon Ability Names", "")),
                    "weapon_keyword_names": split_list(row.get("Weapon Keyword Names", "")),
                    "is_base_equipment":    clean(row.get("Is Base Equipment")),
                }
                weapons.append(weapon_obj)

            # ----------------------------------------------------------
            # wargear_options
            # ----------------------------------------------------------
            wargear_options = []
            for row in wargear_rows:
                if (clean(row.get("Army Name")), clean(row.get("Unit Name"))) != (army_name, unit_name):
                    continue
                wargear_obj = {
                    "model_group":                  clean(row.get("Model Group")),
                    "models_per_trigger":            to_int(row.get("Models Per Trigger")),
                    "max_substitutions_per_trigger": to_int(row.get("Max Substitutions Per Trigger")),
                    "weapon_replaced":               clean(row.get("Weapon Replaced")),
                    "replacement_weapon_name":       clean(row.get("Replacement Weapon Name")),
                    "points_cost":                   to_int(row.get("Points Cost")),
                    "is_choice":                     clean(row.get("Is Choice")),
                    "option_group":                  clean(row.get("Option Group")),
                }
                wargear_options.append(wargear_obj)

            # ----------------------------------------------------------
            # other_options
            # ----------------------------------------------------------
            other_options = []
            for row in other_rows:
                if (clean(row.get("Army Name")), clean(row.get("Unit Name"))) != (army_name, unit_name):
                    continue
                other_obj = {
                    "model_group":          clean(row.get("Model Group")),
                    "option_name":          clean(row.get("Option Name")),
                    "points_cost":          to_int(row.get("Points Cost")),
                    "max_per_unit":         to_int(row.get("Max Per Unit")),
                    "carrier_notes":        clean(row.get("Carrier Notes")),
                    "ability_name":         clean(row.get("Ability Name")),
                    "is_mutually_exclusive": clean(row.get("Is Mutually Exclusive")),
                    "exclusion_group":      clean(row.get("Exclusion Group")),
                }
                other_options.append(other_obj)

            # ----------------------------------------------------------
            # points (flat object, keyed by army + unit name only)
            # ----------------------------------------------------------
            points_row = points_by_key.get((army_name, unit_name))
            if points_row:
                # Size slots: ordered, trailing-blank (D27). Build a list of the
                # size brackets that are actually populated, in order.
                size_slots = [
                    to_int(points_row.get("Size_1")),
                    to_int(points_row.get("Size_2")),
                    to_int(points_row.get("Size_3")),
                ]

                # Points matrix: 3 size rows x 3 unit-copy columns (D28).
                # Stored as a list of size-bracket entries, each carrying the
                # size and the per-copy costs (1st, 2nd, 3rd+ unit).
                # Only emit an entry for a size slot that is populated, so the
                # JSON mirrors the trailing-blank size convention.
                size_entries = []
                for idx, slot in enumerate(["1", "2", "3"]):
                    size_value = size_slots[idx]
                    if size_value is None:
                        continue  # trailing blank size slot — skip
                    size_entries.append({
                        "size":          size_value,
                        "first_unit":    to_int(points_row.get(f"Points_{slot}-1")),
                        "second_unit":   to_int(points_row.get(f"Points_{slot}-2")),
                        "third_plus":    to_int(points_row.get(f"Points_{slot}-3")),
                    })

                points = {
                    "sizes": size_entries,
                }
            else:
                print(f"  WARNING: No points data found for '{army_name}' / '{unit_name}'")
                points = None

            # ----------------------------------------------------------
            # abilities (embedded in full, per model group)
            # ----------------------------------------------------------
            abilities = []
            for row in abilities_rows:
                if (clean(row.get("Army Name")), clean(row.get("Unit Name"))) != (army_name, unit_name):
                    continue
                ability_obj = {
                    "model_group":       clean(row.get("Model Group")),
                    "ability_name":      clean(row.get("Unit Ability Name")),
                    "ability_description": clean(row.get("Unit Ability Description")),
                }
                abilities.append(ability_obj)

            # ----------------------------------------------------------
            # bundled_swaps (merged from bundled_swaps.json, keyed army+unit)
            # ----------------------------------------------------------
            bundled_swaps = bundles.get((army_name, unit_name))

            # A bundle that manages a weapon family OWNS that slot; drop any flat
            # wargear_option whose replaced family the bundle already removes
            # (scoped to model group), so the same swap isn't offered twice.
            if bundled_swaps:
                removed_by_mg = {}
                for grp in bundled_swaps:
                    gmg = grp.get("model_group") or "All"
                    bag = removed_by_mg.setdefault(gmg, set())
                    for ep in grp.get("endpoints", []):
                        for rem in ep.get("removes", []):
                            bag.add(weapon_base(rem))

                def _bundle_owns(wo):
                    rb = weapon_base(wo.get("weapon_replaced"))
                    if not rb:
                        return False
                    wmg = wo.get("model_group") or "All"
                    for gmg, bag in removed_by_mg.items():
                        if (gmg == "All" or gmg == wmg) and rb in bag:
                            return True
                    return False

                kept = [wo for wo in wargear_options if not _bundle_owns(wo)]
                dropped = len(wargear_options) - len(kept)
                if dropped:
                    print(f"  {army_name}/{unit_name}: suppressed {dropped} "
                          f"wargear option(s) owned by a bundle.")
                wargear_options = kept

            # ----------------------------------------------------------
            # Assemble unit object
            # ----------------------------------------------------------
            unit_obj = {
                "unit_name":      unit_name,
                "unit_type":      unit_type,
                "model_groups":   model_groups,
                "weapons":        weapons,
                "wargear_options": wargear_options,
                "other_options":  other_options,
                "bundled_swaps":  bundled_swaps,
                "points":         points,
                "abilities":      abilities,
            }

            army_obj["units"].append(unit_obj)

        output.append(army_obj)

    return output


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="40K Army Builder — CSV to JSON conversion.")
    parser.add_argument("--input-dir", default=INPUT_DIR,
                        help="Folder containing the nine source CSVs.")
    parser.add_argument("--output-dir", default=OUTPUT_DIR,
                        help="Folder to write the JSON outputs into.")
    parser.add_argument("--bundles", default=None,
                        help="Path to bundled_swaps.json. Defaults to "
                             "bundled_swaps.json in the input folder.")
    args = parser.parse_args()

    input_dir  = args.input_dir
    output_dir = args.output_dir
    bundles_path = args.bundles or os.path.join(input_dir, "bundled_swaps.json")

    print(f"\n40K Army Builder — CSV to JSON Conversion")
    print(f"  Input:  {input_dir}")
    print(f"  Output: {output_dir}")
    print()

    # Verify directories exist
    if not os.path.isdir(input_dir):
        print(f"ERROR: Input directory not found: {input_dir}")
        sys.exit(1)
    if not os.path.isdir(output_dir):
        print(f"ERROR: Output directory not found: {output_dir}")
        sys.exit(1)

    print("Loading CSVs...")
    data = load_all(input_dir)
    data["bundles"] = load_bundles(bundles_path)
    print()

    # Build keywords.json
    print("Building keywords.json...")
    keywords = build_keywords(data["keywords"])
    keywords_path = os.path.join(output_dir, "keywords.json")
    with open(keywords_path, "w", encoding="utf-8") as f:
        json.dump(keywords, f, indent=2, ensure_ascii=False)
    print(f"  Written: {keywords_path} ({len(keywords)} keywords)")

    # Build rules.json
    print("Building rules.json...")
    rules = build_rules(data["rules"])
    rules_path = os.path.join(output_dir, "rules.json")
    with open(rules_path, "w", encoding="utf-8") as f:
        json.dump(rules, f, indent=2, ensure_ascii=False)
    print(f"  Written: {rules_path} ({len(rules)} rules)")

    # Build abilities.json
    print("Building abilities.json...")
    abilities = build_abilities(data["unit_abilities"])
    abilities_path = os.path.join(output_dir, "abilities.json")
    with open(abilities_path, "w", encoding="utf-8") as f:
        json.dump(abilities, f, indent=2, ensure_ascii=False)
    print(f"  Written: {abilities_path} ({len(abilities)} abilities)")

    # Build weapon_abilities.json
    print("Building weapon_abilities.json...")
    weapon_abilities = build_weapon_abilities(data["weapon_abilities"])
    weapon_abilities_path = os.path.join(output_dir, "weapon_abilities.json")
    with open(weapon_abilities_path, "w", encoding="utf-8") as f:
        json.dump(weapon_abilities, f, indent=2, ensure_ascii=False)
    print(f"  Written: {weapon_abilities_path} ({len(weapon_abilities)} weapon abilities)")

    # Build units.json
    print("Building units.json...")
    units = build_units(data)
    units_path = os.path.join(output_dir, "units.json")
    with open(units_path, "w", encoding="utf-8") as f:
        json.dump(units, f, indent=2, ensure_ascii=False)
    total_units = sum(len(a["units"]) for a in units)
    print(f"  Written: {units_path} ({len(units)} armies, {total_units} units)")

    print("\nConversion complete.")


if __name__ == "__main__":
    main()
